export const banks = [
  {
    id: 1,
    name: "State Bank of India",
    pincode: 590003,
    branch: "Khasabag",
    location: "Teachers Colony, Khasabag, Belagavi, India",
  },
  {
    id: 2,
    name: "Industrial & Commercial Bank of China",
    pincode: 100000,
    branch: "Beijing",
    location: "Beijing, China",
  },
  {
    id: 3,
    name: "China Construction Bank",
    pincode: 200000,
    branch: "Shanghai",
    location: "Shanghai, China",
  },
  {
    id: 4,
    name: "Agricultural Bank of China",
    pincode: 300000,
    branch: "Beijing",
    location: "Beijing, China",
  },
  {
    id: 5,
    name: "JPMorgan Chase",
    pincode: 10179,
    branch: "New York",
    location: "New York City, USA",
  },
  {
    id: 6,
    name: "Bank of America",
    pincode: 10020,
    branch: "New York",
    location: "New York City, USA",
  },
  {
    id: 7,
    name: "Wells Fargo",
    pincode: 94105,
    branch: "San Francisco",
    location: "San Francisco, USA",
  },
  {
    id: 8,
    name: "HSBC Holdings",
    pincode: 120101,
    branch: "London",
    location: "London, UK",
  },
  {
    id: 9,
    name: "Citigroup",
    pincode: 10022,
    branch: "New York",
    location: "New York City, USA",
  },
  {
    id: 10,
    name: "Mitsubishi UFJ Financial Group",
    pincode: 1008086,
    branch: "Tokyo",
    location: "Tokyo, Japan",
  },
];
